### PR TITLE
Ben

### PR DESCRIPTION
**Pull request by BenJS1993**
Finished login, done staff overview and started staff details.

### CODE REVIEW

**Review by haze-bear — DISMISSED** [review]
No parent component needed, happy to merge as it is

**Comment by BenJS1993** [comment]
Updated the Staff Details by changing the headings, and I've created 4 cells for the contacts section to include Name, Relationship, Phone 1 and Phone 2.

**Comment by BenJS1993** [comment]
Fixed the issue with Staff Details jsx, and added columns to the table headings and cells.

**Review by haze-bear — APPROVED** [review]
Secondary review before master merge, im happy with this all though looks fab

**Pull request merged**
