### PR TITLE
clock in and out and add user form added

### PR DESCRIPTION
**Pull request by opholroyd**

### CODE REVIEW

**Comment by connorrooney** [comment]
Can you change it from logging to the console to it logging/displaying the clock in/current time on the screen similar to the figma.

**Review by haze-bear — CHANGES_REQUESTED** [review]
Print to page in H1 tag or something similar instead of printing to console only

**Review by haze-bear — DISMISSED** [review]
Looks good, cheers for changing, happy to merge now.

**Review by haze-bear — DISMISSED** [review]
Slight changes to function in App.js, clocking in/out times already stored in state so passed to props instead of "getElementById" code.

**Review by haze-bear — APPROVED** [review]
late merge

**Pull request merged**
